swagger: '2.0'
info:
  title: API Documentation
  version: 1.0.0
  description: |
    Write your description here.
host: localhost
schemes:
  - https
basePath: /api
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
  - application/json
  - application/xml
  - application/octet-stream
produces:
  - application/json
	- application/xml
paths:
  '__default':
    post:
      produces:
        - application/json
        - application/xml
      parameters:
        -
          $ref: '#/parameters/header_X-Auth-Token'
        -
          $ref: '#/parameters/header_Accept-Charset'
        -
          $ref: '#/parameters/header_Accept'
      responses:
        200:
          description: success
        400:
          description: error
parameters:
  header_X-Auth-Token:
    in: header
    name: Authorization
    description: API access token
    required: true
    type: string
  header_Accept-Charset:
    in: header
    name: Accept-Charset
    required: true
    type: string
    default: "utf-8"
  header_Accept:
    in: header
    name: Accept
    required: true
    type: string
    default: "application/json"

